### PR TITLE
Add NetBSD install instruction for Ruby version

### PR DESCRIPTION
**Pull request by spenserblack**
## To do checklist

- [ ] Update/create `RELEASE_NOTES` file if necessary

### CODE REVIEW

**Comment by spenserblack** [comment]
@0323pin Anything I should add/change?

**Comment by 0323pin** [comment]
> @0323pin Anything I should add/change?

For now, it's fine. Thanks!
We were planning on removing the Rust version from the repository, let me know if we should keep it.

**Comment by spenserblack** [comment]
>We were planning on removing the Rust version from the repository

That's a good idea, best to have only one version floating out there :+1:
If anyone *really* wants to use the Rust version, they can always compile from source.

The `ruby-` prefix will be kept, right?

**Comment by 0323pin** [comment]
> The ruby- prefix will be kept, right?

Yes

**Pull request merged**
